theme: jekyll-theme-hacker
title: "United Geekdom web journal"
webrick:
  headers:
    My-Header: "<a href='/index.html'>Home</a> | <a href='/games/'>Games</a> | <a href='/charnimation/'>CHARnimation</a> | <a href='/archive/'>Archive</a>"
    My-Other-Header: title
